import { BaseApiClient, IBaseApiClientConfigs } from "./BaseApiClient";

export class StudentAPIs extends BaseApiClient {
    protected basePath: string;

    constructor(baseApiClientConfigs: IBaseApiClientConfigs, basePath?: string) {
        super(baseApiClientConfigs)
        this.basePath = basePath || '/students';
    }

    async fetchUserData(): Promise<any> {
        const responseData = await this.getCall<any>(`/healthcheck`);
        if (!responseData) throw new Error(`Error Fetching Bundle Details`);
        return responseData;
    }

    async getAutogeneratedAdmissionNumber(courseId: string, dateOfAdmission: Date): Promise<string> {
        const reqUrl =`${this.basePath}/admno?courseId=${courseId}&dateOfAdmission=${dateOfAdmission.toISOString()}`
        const responseData = await this.getCall<any>(reqUrl);
        if (!responseData) throw new Error(`Error Fetching Bundle Details`);
        return responseData.admissionNumber;
    }

}