import { IListPagination } from "../common/interface/global";
import { IAddStudentWizardState, IStudentListFilters, IStudentsModel } from "../common/interface/student";
import APIs from "./apis";
import { IPaginatedData } from "./models/common/interfaces";
import { addStudentWizardStateFormSchemaToCreateStudentRequestSchema } from "./models/rest/student/createStudent";

const getAutogeneratedAdmissionNumber = (courseId: string, dateOfAdmission: Date): Promise<string> => {
    return APIs.studentAPIs().getAutogeneratedAdmissionNumber(courseId, dateOfAdmission);
}
const createStudent = (studentData: IAddStudentWizardState['forms']): Promise<IStudentsModel> => {
    const createStudentData = addStudentWizardStateFormSchemaToCreateStudentRequestSchema(studentData)
    return APIs.studentAPIs().createStudent(createStudentData)
}
const getPaginatedStudentList =
    (studentListPagination: IListPagination, appliedStudentListFilters: IStudentListFilters)
        : Promise<IPaginatedData<IStudentsModel>> => {
        return APIs.studentAPIs().getPaginatedStudentList(studentListPagination, appliedStudentListFilters);
    }
const studentServices = {
    createStudent,
    getAutogeneratedAdmissionNumber,
    getPaginatedStudentList
}

export default studentServices;