import APIs from "./apis";

const getAutogeneratedAdmissionNumber = (courseId: string, dateOfAdmission: Date): Promise<string> => {
    return APIs.studentAPIs().getAutogeneratedAdmissionNumber(courseId, dateOfAdmission);
}
const studentServices = {
    getAutogeneratedAdmissionNumber
}

export default studentServices;