import express, { NextFunction, Request, Response } from 'express';
import { IAppFeatures } from '../../interfaces/appFeatures';
import { IAppConfig } from '../../config';
import { HttpStatusCode } from '../../enums/httpStatusCode';
import { BaseController } from '../BaseController';
import { ICourseService, CourseService } from './CourseServices';
import { createCourseValidationSchema } from '../../models/validators/course';
import { CourseDTO } from '../../models/domain/CourseDTO';
import { ICreateCourseRequestSchema } from '../../models/rest/course/createCourse';
import { CourseStatus } from '../../enums/course';
import { IGetPaginatedCourseListFiltersSchema } from '../../models/rest/course/getPaginatedCourseList';

interface IGetPaginatedCourseListRequestSchema { page: number, limit: number, search?: string, status?: CourseStatus }
export class CoursesController extends BaseController {
  public basePath: string;
  public courseServices: ICourseService;
  public courseDTO: CourseDTO;

  constructor(appConfig: IAppConfig, appFeatures?: IAppFeatures) {
    super(appConfig, { basePath: '/courses', moduleName: 'Courses Controller' }, appFeatures);
    this.router = express.Router();
    this.courseServices = new CourseService(appConfig, appFeatures);
    this.courseDTO = new CourseDTO();
    this.intializeRoutes();
  }

  public getBasePath(): string {
    return this.basePath;
  }

  public intializeRoutes(): void {
    this.router.get(this.basePath, [
      this.transactionLogger.logTransaction(`Get All Courses`),
      this.asyncHandler(this.getPaginatedCourseList)
    ]);
    this.router.post(this.basePath, [
      this.transactionLogger.logTransaction(`Create New Course`),
      this.validateAll(createCourseValidationSchema),
      this.asyncHandler(this.createCourse),
    ]);
    this.router.get(`${this.basePath}/menu`, [
      this.transactionLogger.logTransaction(`Get Courses Menu List`),
      this.asyncHandler(this.getCourseMenuList)
    ]);
    this.router.get(`${this.basePath}/autogen`, [
      this.transactionLogger.logTransaction(`Get autogenerated course code`),
      this.asyncHandler(this.getNextCourseCode)
    ]);
  }
  private getNextCourseCode = async (request: Request, response: Response, next: NextFunction) => {
    const index = await this.courseServices.getNextCourseCode();
    const courseCode = this.courseServices.generateCode("COURSE", index)
    this.sendResponse(response, HttpStatusCode.OK, { status: HttpStatusCode.OK, txId: request.txId, courseCode });
  }
  private getCourseMenuList = async (request: Request, response: Response, next: NextFunction) => {
    const courseMenuList = await this.courseServices.getCourseMenuList();
    this.sendResponse(response, HttpStatusCode.OK, { status: HttpStatusCode.OK, txId: request.txId, courseMenuList });
  }

  private getPaginatedCourseList = async (request: Request, response: Response, next: NextFunction) => {
    const { page, limit, search, status }: IGetPaginatedCourseListRequestSchema = {
      page: Number(request.query.page),
      limit: Number(request.query.limit),
      search: request.query.search as string,
      status: request.query.status as CourseStatus,
    };
    const filters: IGetPaginatedCourseListFiltersSchema = { search, status };
    const coursesList = await this.courseServices.getPaginatedCourseList(page, limit, filters);
    this.sendResponse(response, HttpStatusCode.OK, { status: HttpStatusCode.OK, txId: request.txId, coursesList });
  };

  private createCourse = async (request: Request, response: Response, next: NextFunction) => {
    const createData: ICreateCourseRequestSchema = request.body;
    const courseCode = await this.courseServices.getNextCourseCode();
    const courseData = await this.courseServices.createCourse(this.courseDTO.fromCreateRequestToDb(createData, courseCode));
    this.sendResponse(response, HttpStatusCode.OK, { status: HttpStatusCode.OK, txId: request.txId, courseData });
  };
}
